export const paths = {
  HOME: '/',
  CSA_DASHBOARD: '/account/csa-profile',
  CART: '/cart',
  CHECKOUT_ORDER_CONFIRMATION: '/checkout/order-confirmation',
  OPEN_PATH_FORM: '/checkout/credit-card',
  CHECKOUT_DELIVERY: '/checkout/shipping-information',
  CHECKOUT_PAYMENT: '/checkout/payment-information',
  CHECKOUT_LOGIN: '/checkout/login',
  PROFILE: '/account/profile',
  ACCOUNT_ADDRESS: '/account/address',
  LOGIN: '/account/login',
  CSA_LOGIN: '/csa-login',
  CREATE_ACCOUNT: '/account/create-account',
  FORGOT_PASSWORD: '/account/forgot-password',
  SSO_VALIDATION: '/account/oidc',
  CONTACT_US: '/contact-us',
  SEARCH: '/search',
}
