# name: Checks

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     types: [opened, synchronize]

# jobs:
#   lint:
#     name: Lint
#     runs-on: ubuntu-latest
#     env:
#       CI: true

#     steps:
#       - name: Authenticate with private NPM package
#         run: echo "${{ secrets.NPM_TOKEN }}" > ~/.npmrc

#       - name: Checkout
#         uses: actions/checkout@v2

#       - name: Install Dependencies
#         uses: actions/setup-node@v1
#         with:
#           node-version: 16.x

#       - run: yarn install --frozen-lockfile

#       - name: Prebuild
#         run: yarn prebuild

#       - name: TypeScript
#         run: yarn ts

#       - name: Lint
#         run: yarn lint

#       - name: CSS Lint
#         run: yarn csslint
